start: code_block

    code_block: statement*

    statement: let_statement
             | function_definition
             | return_statement
             | display_statement
             | if_statement

    let_statement: "let" NAME "=" expr

    function_definition: "def" NAME "(" [args] ")" ":" statement* "end"

    display_statement: "display" "(" expr ")"

    if_statement: "if" expr ":" statement* ("else" ":" statement*)? "end"

    args: expr ("," expr)*

    call: NAME "(" [args] ")"
    
 

    expr: DEC_NUMBER -> number
        | STRING -> string
        | "true" -> boolean_true
        | "false" -> boolean_false
        | call -> call
        | NAME -> name


    return_statement: "return" expr
    COMMENT: /#.*/
    NEWLINE: /(\r?\n)+/
    %ignore COMMENT
    %ignore NEWLINE
    %import python (NAME, DEC_NUMBER, STRING)
    %import common.WS
    %ignore WS